on: push

name: Build and Upload Artifact

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: ./make.sh build

      - name: Fetch commit hash
        id: vars
        run: "echo ::set-output name=sha_short::$(git rev-parse --short \"$GITHUB_SHA\")"

      - run: ./make.sh package ${{ steps.vars.outputs.sha_short }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-package
          path: dist/mod-einsatz-stats-*.zip
          retention-days: 7
