on: push

name: Build and Upload Artifact

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: ./make.sh build
      - run: ./make.sh package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-package
          path: dist/mod-einsatz-stats-*.zip
          retention-days: 7
